/* KukoScrapingFree — textos de la web en los 7 idiomas del programa.
   Cada clave corresponde a un elemento con data-t="clave" (texto) o data-h="clave" (con enlaces). */
window.TEXTOS = {
es: {
  meta_title: "KukoScrapingFree — Scraper de ROMs para Batocera",
  meta_desc: "Scraper de ROMs para Batocera Linux: carátulas, logos, vídeos y fichas de tus juegos desde ScreenScraper. Gratis, en 7 idiomas, para Windows y Linux.",
  nav_features: "Funciones", nav_shots: "Capturas", nav_how: "Cómo funciona", nav_faq: "Preguntas", nav_download: "Descargar gratis",
  lang_label: "Idioma",
  hero_tag: "Scraper de ROMs para Batocera Linux",
  hero_title: "Tu colección retro, con sus carátulas, logos, vídeos y fichas.",
  hero_sub: "KukoScrapingFree busca cada juego en ScreenScraper, descarga sus datos e imágenes en tu idioma y los deja listos para Batocera. Sin tocar nunca tu carpeta de ROMs.",
  btn_download: "Descargar gratis", btn_how: "Cómo funciona",
  badge_free: "100 % gratuito", badge_os: "Windows y Linux", badge_langs: "7 idiomas", badge_systems: "256 sistemas de Batocera",
  stats_visits: "Visitas a la web", stats_downloads: "Descargas", stats_win: "Windows", stats_linux: "Linux",
  stats_note: "Las descargas se cuentan en tiempo real desde GitHub.",
  free_title: "Gratis de verdad, y para siempre",
  free_text: "Sin anuncios, sin suscripciones y sin funciones de pago. Puedes usarlo, copiarlo y compartirlo con quien quieras.",
  scam_title: "¿Te lo han cobrado?",
  scam_text: "Entonces te han estafado. KukoScrapingFree no se vende nunca. Descárgalo solo desde esta web y reclama tu dinero a quien te lo vendió.",
  feat_kicker: "Funciones", feat_title: "Todo lo que necesita tu Batocera, en un solo programa",
  feat_sub: "Pensado para colecciones grandes y para quien no quiere pelearse con ficheros XML.",
  f1_t: "Reconoce tu colección", f1_d: "Detecta los 256 sistemas de Batocera por el nombre de sus carpetas, en tu equipo o en red. Agrupa los juegos de varios discos y aparta las BIOS.",
  f2_t: "Encuentra el juego exacto", f2_d: "Calcula la huella de cada ROM (CRC32, MD5 y SHA1) para que ScreenScraper la identifique sin dudas, aunque el fichero tenga un nombre raro.",
  f3_t: "Tus regiones y tu idioma", f3_d: "Tú decides el orden: España, Europa, Mundial… Las carátulas, los nombres y las fechas salen de tu región preferida, y la sinopsis en tu idioma.",
  f4_t: "Tus ROMs, intactas", f4_d: "Todo se guarda en una carpeta de salida aparte. Al copiarla a Batocera se respetan tus partidas jugadas y tus favoritos.",
  f5_t: "Composiciones a tu gusto", f5_d: "Un editor visual para diseñar la imagen de cada juego: captura, caja 3D, logo y textos, con capas, guías y deshacer.",
  f6_t: "Ficha completa de cada juego", f6_d: "Carátula, galería, vídeo integrado y todos sus datos. Edítalos a mano o vuelve a buscarlos comparando lo nuevo con lo que ya tienes.",
  f7_t: "Revisar y limpiar", f7_d: "Encuentra juegos sin ROM, imágenes que faltan y ficheros que nadie usa. Nada se borra: lo que sobra se aparta en una carpeta.",
  f8_t: "Todo se puede deshacer", f8_d: "Guarda las versiones anteriores de cada gamelist. Vuelve a cualquiera, o al original de Batocera, con un clic.",
  f9_t: "Cuida tu cuenta de ScreenScraper", f9_d: "Respeta los límites de tu cuenta y te avisa antes de un scrapeo grande si no te va a llegar la cuota del día.",
  shots_kicker: "Capturas", shots_title: "Así se ve por dentro",
  s1_t: "La ficha de cada juego", s1_d: "Carátula, logo, composición, sinopsis, valoración y todos los datos del juego en una sola pantalla. Si algo no te convence, lo cambias tú.",
  s2_t: "El editor de composiciones", s2_d: "Diseña la imagen que verás en Batocera colocando capas como en un programa de dibujo. Mira el resultado con tus propios juegos antes de aplicarlo a todo el sistema.",
  s3_t: "Tus preferencias, primero", s3_d: "Elige y ordena las regiones de las que quieres las carátulas y los nombres. Si tu región no existe, se usa la siguiente de tu lista.",
  shots_note: "Las capturas muestran el programa en castellano, con juegos de demostración.",
  mix_title: "Composiciones generadas automáticamente",
  mix_sub: "Ejemplos creados por el programa con la plantilla «Clásica 4:3» (juegos y carátulas de demostración).",
  how_kicker: "Cómo funciona", how_title: "Cuatro pasos y listo",
  h1_t: "Descarga y descomprime", h1_d: "No se instala nada. Todo lo que guarda el programa se queda dentro de su propia carpeta.",
  h2_t: "Escribe tu cuenta de ScreenScraper", h2_d: "Solo tu usuario y tu contraseña de <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Se guardan cifrados en tu equipo.",
  h3_t: "Elige tus carpetas", h3_d: "Tu carpeta de ROMs, en tu disco o en la red (como <code>\\\\BATOCERA\\share\\roms</code>), y dónde guardar el resultado. Un asistente te guía al empezar.",
  h4_t: "Scrapea y copia a Batocera", h4_d: "Marca los sistemas, pulsa «Scrapear selección» y, al terminar, copia la carpeta de salida a tu Batocera.",
  faq_kicker: "Preguntas frecuentes", faq_title: "Lo que suele preguntarse",
  q1: "¿Cuánto cuesta?", a1: "Nada. Es freeware: gratuito y de libre distribución, sin anuncios ni funciones de pago.",
  q2: "¿Necesito una cuenta de ScreenScraper?", a2: "Sí. La cuenta es gratuita y se crea en <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. El programa respeta los límites de tu cuenta: hilos, peticiones por minuto y cuota diaria.",
  q3: "¿Puede estropear mi colección?", a3: "No. Tu carpeta de ROMs nunca se modifica: el programa trabaja sobre una copia en la carpeta de salida, guarda las versiones anteriores de cada gamelist y no borra nada.",
  q4: "¿En qué idiomas está?", a4: "Castellano, inglés, francés, alemán, portugués, ruso e italiano. La sinopsis de los juegos se descarga en el idioma que elijas.",
  q5: "¿Qué necesito para usarlo?", a5: "Un ordenador con Windows o Linux y una pantalla de al menos 1280 × 720. Tu Batocera puede estar en la red: no hace falta sacar el disco.",
  dl_title: "Descarga KukoScrapingFree", dl_sub: "Gratuito · Sin instalación · Para Windows y Linux",
  dl_win: "Descargar para Windows", dl_linux: "Descargar para Linux",
  dl_note: "Descárgalo solo desde esta web: es la única descarga oficial.", dl_version: "Versión {v}",
  badge_update: "Se actualiza solo", q6: "¿Cómo se actualiza el programa?", a6: "Solo. Al abrirse comprueba si hay una versión nueva, te enseña sus novedades y, si aceptas, se descarga, se instala y se vuelve a abrir. Tus datos y tu carpeta de salida no se tocan, y se guarda la versión anterior por si quieres volver a ella. Si tienes la 0.5.40 o una anterior, descarga la nueva desde esta web una sola vez: a partir de ahí llegarán solas.",
  ver_line: "Versión {v} · actualizada el {d} a las {t}", disc_title: "Descargo de responsabilidad", disc_text: "KukoScrapingFree se ofrece «tal cual», sin garantías de ningún tipo, y puede contener errores. <b>Haz una copia de seguridad</b> de tus ROMs y de tus gamelist.xml antes de usarlo y antes de copiar nada a tu Batocera. Cada usuario es responsable de los cambios que haga en su sistema y asume el riesgo de usar el programa: el autor no se hace responsable de los daños ni de las pérdidas de datos que pueda causar.", disc_dl: "Al descargarlo aceptas el <a href=\"#aviso\">descargo de responsabilidad</a>.",
  ss_title: "Gracias a ScreenScraper",
  ss_text: "La información, las imágenes y los vídeos de los juegos proceden de <a href=\"https://www.screenscraper.fr\">ScreenScraper.fr</a>, una gran base de datos creada y mantenida por su comunidad. Gracias por permitir usar su API para dar servicio a este programa. Los datos y las imágenes pertenecen a ScreenScraper y a sus autores.",
  foot_by: "Creado por <b>Kukoman</b> · © 2026 · Freeware · <a href=\"https://github.com/kukoxbmc/KukoScrapingFree-web\">GitHub</a>",
  foot_indep: "Proyecto independiente. Batocera y ScreenScraper pertenecen a sus respectivos autores.",
  alt_main: "Ventana principal de KukoScrapingFree con la lista de sistemas y los juegos de Super Nintendo",
  alt_sheet: "Ficha de un juego con carátula, sinopsis, galería e información",
  alt_editor: "Editor de composiciones con capas, lienzo y propiedades",
  alt_regions: "Ajustes de regiones con banderas y orden de preferencia",
  alt_mix: "Composición de ejemplo generada por el programa"
},
en: {
  meta_title: "KukoScrapingFree — ROM scraper for Batocera",
  meta_desc: "ROM scraper for Batocera Linux: box art, logos, videos and game info from ScreenScraper. Free, in 7 languages, for Windows and Linux.",
  nav_features: "Features", nav_shots: "Screenshots", nav_how: "How it works", nav_faq: "FAQ", nav_download: "Free download",
  lang_label: "Language",
  hero_tag: "ROM scraper for Batocera Linux",
  hero_title: "Your retro collection, with its box art, logos, videos and game info.",
  hero_sub: "KukoScrapingFree looks up every game on ScreenScraper, downloads its data and images in your language and gets them ready for Batocera. Without ever touching your ROM folder.",
  btn_download: "Free download", btn_how: "How it works",
  badge_free: "100% free", badge_os: "Windows and Linux", badge_langs: "7 languages", badge_systems: "256 Batocera systems",
  stats_visits: "Website visits", stats_downloads: "Downloads", stats_win: "Windows", stats_linux: "Linux",
  stats_note: "Downloads are counted in real time from GitHub.",
  free_title: "Truly free, forever",
  free_text: "No ads, no subscriptions and no paid features. You can use it, copy it and share it with anyone.",
  scam_title: "Did someone charge you for it?",
  scam_text: "Then you have been scammed. KukoScrapingFree is never sold. Only download it from this website and ask the seller for your money back.",
  feat_kicker: "Features", feat_title: "Everything your Batocera needs, in a single program",
  feat_sub: "Designed for large collections and for anyone who doesn't want to wrestle with XML files.",
  f1_t: "Recognises your collection", f1_d: "Detects all 256 Batocera systems from their folder names, on your computer or over the network. Groups multi-disc games and sets BIOS files aside.",
  f2_t: "Finds the exact game", f2_d: "Calculates each ROM's fingerprint (CRC32, MD5 and SHA1) so ScreenScraper identifies it with certainty, even if the file has an odd name.",
  f3_t: "Your regions and your language", f3_d: "You choose the order: Spain, Europe, World… Box art, names and dates come from your preferred region, and the synopsis in your language.",
  f4_t: "Your ROMs, untouched", f4_d: "Everything is saved to a separate output folder. When you copy it to Batocera, your play history and favourites are kept.",
  f5_t: "Compositions your way", f5_d: "A visual editor to design each game's image: screenshot, 3D box, logo and text, with layers, guides and undo.",
  f6_t: "Full game sheet", f6_d: "Box art, gallery, built-in video and all its data. Edit it by hand or look it up again, comparing the new data with what you already have.",
  f7_t: "Review and clean", f7_d: "Finds games without a ROM, missing images and files nobody uses. Nothing is deleted: leftovers are moved to a folder.",
  f8_t: "Everything can be undone", f8_d: "Keeps earlier versions of each gamelist. Go back to any of them, or to the Batocera original, with one click.",
  f9_t: "Looks after your ScreenScraper account", f9_d: "Respects your account limits and warns you before a big scrape if your daily quota won't be enough.",
  shots_kicker: "Screenshots", shots_title: "A look inside",
  s1_t: "Every game's sheet", s1_d: "Box art, logo, composition, synopsis, rating and all the game's data on one screen. If something doesn't convince you, change it yourself.",
  s2_t: "The composition editor", s2_d: "Design the image you'll see in Batocera by placing layers, like in a drawing program. Preview it with your own games before applying it to the whole system.",
  s3_t: "Your preferences first", s3_d: "Choose and order the regions you want box art and names from. If your region doesn't exist, the next one on your list is used.",
  shots_note: "Screenshots show the program in Spanish, with demo games.",
  mix_title: "Automatically generated compositions",
  mix_sub: "Examples created by the program with the «Classic 4:3» template (demo games and box art).",
  how_kicker: "How it works", how_title: "Four steps and you're done",
  h1_t: "Download and unzip", h1_d: "Nothing is installed. Everything the program saves stays inside its own folder.",
  h2_t: "Enter your ScreenScraper account", h2_d: "Just your <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a> user name and password. They are stored encrypted on your computer.",
  h3_t: "Choose your folders", h3_d: "Your ROM folder, on your disk or on the network (such as <code>\\\\BATOCERA\\share\\roms</code>), and where to save the result. A wizard guides you at the start.",
  h4_t: "Scrape and copy to Batocera", h4_d: "Tick the systems, click «Scrape selection» and, when it finishes, copy the output folder to your Batocera.",
  faq_kicker: "FAQ", faq_title: "Frequently asked questions",
  q1: "How much does it cost?", a1: "Nothing. It's freeware: free and freely distributable, with no ads or paid features.",
  q2: "Do I need a ScreenScraper account?", a2: "Yes. The account is free and is created at <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. The program respects your account limits: threads, requests per minute and daily quota.",
  q3: "Can it damage my collection?", a3: "No. Your ROM folder is never modified: the program works on a copy in the output folder, keeps earlier versions of each gamelist and deletes nothing.",
  q4: "Which languages is it in?", a4: "Spanish, English, French, German, Portuguese, Russian and Italian. Game synopses are downloaded in the language you choose.",
  q5: "What do I need to use it?", a5: "A computer with Windows or Linux and a screen of at least 1280 × 720. Your Batocera can be on the network: no need to remove the disk.",
  dl_title: "Download KukoScrapingFree", dl_sub: "Free · No installation · For Windows and Linux",
  dl_win: "Download for Windows", dl_linux: "Download for Linux",
  dl_note: "Only download it from this website: it is the only official download.", dl_version: "Version {v}",
  badge_update: "Updates itself", q6: "How is the program updated?", a6: "By itself. When it starts it checks for a new version, shows you what's new and, if you accept, downloads it, installs it and reopens. Your data and your output folder are not touched, and the previous version is kept in case you want to go back. If you have 0.5.40 or older, download the new one from this website just once: from then on, updates arrive by themselves.",
  ver_line: "Version {v} · updated on {d} at {t}", disc_title: "Disclaimer", disc_text: "KukoScrapingFree is provided “as is”, without any warranty, and may contain errors. <b>Back up</b> your ROMs and your gamelist.xml files before using it and before copying anything to your Batocera. Each user is responsible for the changes they make to their system and uses the program at their own risk: the author accepts no liability for any damage or data loss it may cause.", disc_dl: "By downloading it you accept the <a href=\"#aviso\">disclaimer</a>.",
  ss_title: "Thanks to ScreenScraper",
  ss_text: "Game information, images and videos come from <a href=\"https://www.screenscraper.fr\">ScreenScraper.fr</a>, a large database created and maintained by its community. Thank you for allowing this program to use your API. The data and images belong to ScreenScraper and their authors.",
  foot_by: "Created by <b>Kukoman</b> · © 2026 · Freeware · <a href=\"https://github.com/kukoxbmc/KukoScrapingFree-web\">GitHub</a>",
  foot_indep: "Independent project. Batocera and ScreenScraper belong to their respective owners.",
  alt_main: "KukoScrapingFree main window with the list of systems and Super Nintendo games",
  alt_sheet: "Game sheet with box art, synopsis, gallery and details",
  alt_editor: "Composition editor with layers, canvas and properties",
  alt_regions: "Region settings with flags and order of preference",
  alt_mix: "Example composition generated by the program"
},
fr: {
  meta_title: "KukoScrapingFree — Scraper de ROM pour Batocera",
  meta_desc: "Scraper de ROM pour Batocera Linux : jaquettes, logos, vidéos et fiches de vos jeux depuis ScreenScraper. Gratuit, en 7 langues, pour Windows et Linux.",
  nav_features: "Fonctions", nav_shots: "Captures", nav_how: "Fonctionnement", nav_faq: "Questions", nav_download: "Télécharger gratuitement",
  lang_label: "Langue",
  hero_tag: "Scraper de ROM pour Batocera Linux",
  hero_title: "Votre collection rétro, avec ses jaquettes, logos, vidéos et fiches.",
  hero_sub: "KukoScrapingFree recherche chaque jeu sur ScreenScraper, télécharge ses données et images dans votre langue et les prépare pour Batocera. Sans jamais toucher à votre dossier de ROM.",
  btn_download: "Télécharger gratuitement", btn_how: "Fonctionnement",
  badge_free: "100 % gratuit", badge_os: "Windows et Linux", badge_langs: "7 langues", badge_systems: "256 systèmes Batocera",
  stats_visits: "Visites du site", stats_downloads: "Téléchargements", stats_win: "Windows", stats_linux: "Linux",
  stats_note: "Les téléchargements sont comptés en temps réel depuis GitHub.",
  free_title: "Vraiment gratuit, pour toujours",
  free_text: "Sans publicité, sans abonnement et sans fonctions payantes. Vous pouvez l'utiliser, le copier et le partager avec qui vous voulez.",
  scam_title: "On vous l'a fait payer ?",
  scam_text: "Alors vous avez été arnaqué. KukoScrapingFree n'est jamais vendu. Téléchargez-le uniquement depuis ce site et demandez le remboursement à la personne qui vous l'a vendu.",
  feat_kicker: "Fonctions", feat_title: "Tout ce dont votre Batocera a besoin, dans un seul programme",
  feat_sub: "Conçu pour les grandes collections et pour ceux qui ne veulent pas se battre avec des fichiers XML.",
  f1_t: "Reconnaît votre collection", f1_d: "Détecte les 256 systèmes de Batocera d'après le nom de leurs dossiers, sur votre ordinateur ou en réseau. Regroupe les jeux multi-disques et met les BIOS de côté.",
  f2_t: "Trouve le jeu exact", f2_d: "Calcule l'empreinte de chaque ROM (CRC32, MD5 et SHA1) pour que ScreenScraper l'identifie sans erreur, même si le fichier porte un nom étrange.",
  f3_t: "Vos régions et votre langue", f3_d: "Vous choisissez l'ordre : Espagne, Europe, Monde… Jaquettes, noms et dates viennent de votre région préférée, et le résumé dans votre langue.",
  f4_t: "Vos ROM intactes", f4_d: "Tout est enregistré dans un dossier de sortie séparé. En le copiant sur Batocera, vos parties jouées et vos favoris sont conservés.",
  f5_t: "Des compositions à votre goût", f5_d: "Un éditeur visuel pour concevoir l'image de chaque jeu : capture, boîte 3D, logo et textes, avec calques, repères et annulation.",
  f6_t: "Fiche complète de chaque jeu", f6_d: "Jaquette, galerie, vidéo intégrée et toutes ses données. Modifiez-les à la main ou relancez la recherche en comparant le nouveau avec l'existant.",
  f7_t: "Vérifier et nettoyer", f7_d: "Trouve les jeux sans ROM, les images manquantes et les fichiers inutilisés. Rien n'est supprimé : le superflu est mis de côté dans un dossier.",
  f8_t: "Tout peut être annulé", f8_d: "Conserve les versions précédentes de chaque gamelist. Revenez à n'importe laquelle, ou à l'original de Batocera, en un clic.",
  f9_t: "Prend soin de votre compte ScreenScraper", f9_d: "Respecte les limites de votre compte et vous prévient avant un gros scrape si votre quota du jour ne suffit pas.",
  shots_kicker: "Captures", shots_title: "Un aperçu de l'intérieur",
  s1_t: "La fiche de chaque jeu", s1_d: "Jaquette, logo, composition, résumé, note et toutes les données du jeu sur un seul écran. Si quelque chose ne vous convient pas, vous le changez.",
  s2_t: "L'éditeur de compositions", s2_d: "Concevez l'image que vous verrez dans Batocera en plaçant des calques, comme dans un logiciel de dessin. Vérifiez le résultat avec vos propres jeux avant de l'appliquer à tout le système.",
  s3_t: "Vos préférences d'abord", s3_d: "Choisissez et ordonnez les régions d'où viennent les jaquettes et les noms. Si votre région n'existe pas, la suivante de votre liste est utilisée.",
  shots_note: "Les captures montrent le programme en espagnol, avec des jeux de démonstration.",
  mix_title: "Compositions générées automatiquement",
  mix_sub: "Exemples créés par le programme avec le modèle « Classique 4:3 » (jeux et jaquettes de démonstration).",
  how_kicker: "Fonctionnement", how_title: "Quatre étapes et c'est prêt",
  h1_t: "Téléchargez et décompressez", h1_d: "Rien à installer. Tout ce que le programme enregistre reste dans son propre dossier.",
  h2_t: "Saisissez votre compte ScreenScraper", h2_d: "Juste votre identifiant et votre mot de passe <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Ils sont enregistrés chiffrés sur votre ordinateur.",
  h3_t: "Choisissez vos dossiers", h3_d: "Votre dossier de ROM, sur votre disque ou en réseau (comme <code>\\\\BATOCERA\\share\\roms</code>), et où enregistrer le résultat. Un assistant vous guide au départ.",
  h4_t: "Scrapez et copiez sur Batocera", h4_d: "Cochez les systèmes, cliquez sur « Scraper la sélection » et, à la fin, copiez le dossier de sortie sur votre Batocera.",
  faq_kicker: "Questions fréquentes", faq_title: "Ce que l'on demande souvent",
  q1: "Combien ça coûte ?", a1: "Rien. C'est un freeware : gratuit et librement distribuable, sans publicité ni fonctions payantes.",
  q2: "Faut-il un compte ScreenScraper ?", a2: "Oui. Le compte est gratuit et se crée sur <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Le programme respecte les limites de votre compte : threads, requêtes par minute et quota quotidien.",
  q3: "Peut-il abîmer ma collection ?", a3: "Non. Votre dossier de ROM n'est jamais modifié : le programme travaille sur une copie dans le dossier de sortie, conserve les versions précédentes de chaque gamelist et ne supprime rien.",
  q4: "Dans quelles langues est-il disponible ?", a4: "Espagnol, anglais, français, allemand, portugais, russe et italien. Les résumés des jeux sont téléchargés dans la langue de votre choix.",
  q5: "De quoi ai-je besoin ?", a5: "Un ordinateur sous Windows ou Linux et un écran d'au moins 1280 × 720. Votre Batocera peut être en réseau : pas besoin de sortir le disque.",
  dl_title: "Télécharger KukoScrapingFree", dl_sub: "Gratuit · Sans installation · Pour Windows et Linux",
  dl_win: "Télécharger pour Windows", dl_linux: "Télécharger pour Linux",
  dl_note: "Téléchargez-le uniquement sur ce site : c’est le seul téléchargement officiel.", dl_version: "Version {v}",
  badge_update: "Mise à jour automatique", q6: "Comment le programme se met-il à jour ?", a6: "Tout seul. Au démarrage, il vérifie s'il existe une nouvelle version, te montre les nouveautés et, si tu acceptes, la télécharge, l'installe et se rouvre. Tes données et ton dossier de sortie ne sont pas touchés, et la version précédente est conservée au cas où tu voudrais y revenir. Si tu as la 0.5.40 ou une plus ancienne, télécharge la nouvelle depuis ce site une seule fois : ensuite, les mises à jour arriveront toutes seules.",
  ver_line: "Version {v} · mise à jour le {d} à {t}", disc_title: "Avertissement", disc_text: "KukoScrapingFree est fourni « tel quel », sans aucune garantie, et peut contenir des erreurs. <b>Fais une sauvegarde</b> de tes ROM et de tes gamelist.xml avant de l'utiliser et avant de copier quoi que ce soit sur ton Batocera. Chaque utilisateur est responsable des modifications qu'il apporte à son système et utilise le programme à ses risques : l'auteur décline toute responsabilité pour les dommages ou pertes de données qu'il pourrait causer.", disc_dl: "En le téléchargeant, tu acceptes l'<a href=\"#aviso\">avertissement</a>.",
  ss_title: "Merci à ScreenScraper",
  ss_text: "Les informations, images et vidéos des jeux proviennent de <a href=\"https://www.screenscraper.fr\">ScreenScraper.fr</a>, une grande base de données créée et entretenue par sa communauté. Merci de permettre à ce programme d'utiliser votre API. Les données et les images appartiennent à ScreenScraper et à leurs auteurs.",
  foot_by: "Créé par <b>Kukoman</b> · © 2026 · Freeware · <a href=\"https://github.com/kukoxbmc/KukoScrapingFree-web\">GitHub</a>",
  foot_indep: "Projet indépendant. Batocera et ScreenScraper appartiennent à leurs auteurs respectifs.",
  alt_main: "Fenêtre principale de KukoScrapingFree avec la liste des systèmes et les jeux Super Nintendo",
  alt_sheet: "Fiche d'un jeu avec jaquette, résumé, galerie et informations",
  alt_editor: "Éditeur de compositions avec calques, canevas et propriétés",
  alt_regions: "Réglages des régions avec drapeaux et ordre de préférence",
  alt_mix: "Composition d'exemple générée par le programme"
},
de: {
  meta_title: "KukoScrapingFree — ROM-Scraper für Batocera",
  meta_desc: "ROM-Scraper für Batocera Linux: Cover, Logos, Videos und Spielinfos von ScreenScraper. Kostenlos, in 7 Sprachen, für Windows und Linux.",
  nav_features: "Funktionen", nav_shots: "Screenshots", nav_how: "So funktioniert's", nav_faq: "Fragen", nav_download: "Kostenlos herunterladen",
  lang_label: "Sprache",
  hero_tag: "ROM-Scraper für Batocera Linux",
  hero_title: "Deine Retro-Sammlung, mit Covern, Logos, Videos und Spielinfos.",
  hero_sub: "KukoScrapingFree sucht jedes Spiel bei ScreenScraper, lädt Daten und Bilder in deiner Sprache herunter und bereitet sie für Batocera vor. Ohne deinen ROM-Ordner je anzurühren.",
  btn_download: "Kostenlos herunterladen", btn_how: "So funktioniert's",
  badge_free: "100 % kostenlos", badge_os: "Windows und Linux", badge_langs: "7 Sprachen", badge_systems: "256 Batocera-Systeme",
  stats_visits: "Besuche der Website", stats_downloads: "Downloads", stats_win: "Windows", stats_linux: "Linux",
  stats_note: "Die Downloads werden in Echtzeit bei GitHub gezählt.",
  free_title: "Wirklich kostenlos, für immer",
  free_text: "Keine Werbung, keine Abos und keine kostenpflichtigen Funktionen. Du darfst es nutzen, kopieren und mit allen teilen.",
  scam_title: "Hast du dafür bezahlt?",
  scam_text: "Dann wurdest du betrogen. KukoScrapingFree wird nie verkauft. Lade es nur von dieser Website herunter und fordere dein Geld vom Verkäufer zurück.",
  feat_kicker: "Funktionen", feat_title: "Alles, was dein Batocera braucht, in einem Programm",
  feat_sub: "Gemacht für große Sammlungen und für alle, die sich nicht mit XML-Dateien herumschlagen wollen.",
  f1_t: "Erkennt deine Sammlung", f1_d: "Erkennt alle 256 Batocera-Systeme am Namen ihrer Ordner, lokal oder im Netzwerk. Fasst Spiele mit mehreren Discs zusammen und legt BIOS-Dateien beiseite.",
  f2_t: "Findet das richtige Spiel", f2_d: "Berechnet den Fingerabdruck jeder ROM (CRC32, MD5 und SHA1), damit ScreenScraper sie sicher erkennt, auch bei seltsamen Dateinamen.",
  f3_t: "Deine Regionen und deine Sprache", f3_d: "Du bestimmst die Reihenfolge: Spanien, Europa, Welt… Cover, Namen und Daten kommen aus deiner bevorzugten Region, die Beschreibung in deiner Sprache.",
  f4_t: "Deine ROMs bleiben unberührt", f4_d: "Alles wird in einem eigenen Ausgabeordner gespeichert. Beim Kopieren zu Batocera bleiben deine Spielstände und Favoriten erhalten.",
  f5_t: "Kompositionen nach deinem Geschmack", f5_d: "Ein visueller Editor für das Bild jedes Spiels: Screenshot, 3D-Box, Logo und Texte, mit Ebenen, Hilfslinien und Rückgängig.",
  f6_t: "Komplettes Datenblatt jedes Spiels", f6_d: "Cover, Galerie, eingebautes Video und alle Daten. Bearbeite sie von Hand oder suche sie erneut und vergleiche Neues mit Vorhandenem.",
  f7_t: "Prüfen und aufräumen", f7_d: "Findet Spiele ohne ROM, fehlende Bilder und ungenutzte Dateien. Nichts wird gelöscht: Überflüssiges wird in einen Ordner verschoben.",
  f8_t: "Alles lässt sich rückgängig machen", f8_d: "Bewahrt frühere Versionen jeder Gamelist auf. Kehre mit einem Klick zu jeder davon oder zum Batocera-Original zurück.",
  f9_t: "Schont dein ScreenScraper-Konto", f9_d: "Hält die Grenzen deines Kontos ein und warnt dich vor einem großen Scrape, wenn dein Tageskontingent nicht reicht.",
  shots_kicker: "Screenshots", shots_title: "Ein Blick ins Programm",
  s1_t: "Das Datenblatt jedes Spiels", s1_d: "Cover, Logo, Komposition, Beschreibung, Bewertung und alle Spieldaten auf einem Bildschirm. Wenn dir etwas nicht gefällt, änderst du es selbst.",
  s2_t: "Der Kompositionseditor", s2_d: "Gestalte das Bild, das du in Batocera siehst, mit Ebenen wie in einem Zeichenprogramm. Prüfe das Ergebnis mit deinen eigenen Spielen, bevor du es auf das ganze System anwendest.",
  s3_t: "Deine Vorlieben zuerst", s3_d: "Wähle und ordne die Regionen, aus denen Cover und Namen kommen sollen. Gibt es deine Region nicht, wird die nächste aus deiner Liste genommen.",
  shots_note: "Die Screenshots zeigen das Programm auf Spanisch, mit Demo-Spielen.",
  mix_title: "Automatisch erzeugte Kompositionen",
  mix_sub: "Beispiele, die das Programm mit der Vorlage „Klassisch 4:3“ erstellt hat (Demo-Spiele und -Cover).",
  how_kicker: "So funktioniert's", how_title: "Vier Schritte, fertig",
  h1_t: "Herunterladen und entpacken", h1_d: "Es wird nichts installiert. Alles, was das Programm speichert, bleibt in seinem eigenen Ordner.",
  h2_t: "ScreenScraper-Konto eingeben", h2_d: "Nur dein Benutzername und Passwort von <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Sie werden verschlüsselt auf deinem Computer gespeichert.",
  h3_t: "Ordner wählen", h3_d: "Dein ROM-Ordner, lokal oder im Netzwerk (z. B. <code>\\\\BATOCERA\\share\\roms</code>), und wo das Ergebnis gespeichert wird. Ein Assistent führt dich am Anfang.",
  h4_t: "Scrapen und zu Batocera kopieren", h4_d: "Systeme markieren, auf „Auswahl scrapen“ klicken und danach den Ausgabeordner auf dein Batocera kopieren.",
  faq_kicker: "Häufige Fragen", faq_title: "Was oft gefragt wird",
  q1: "Was kostet es?", a1: "Nichts. Es ist Freeware: kostenlos und frei weitergebbar, ohne Werbung oder kostenpflichtige Funktionen.",
  q2: "Brauche ich ein ScreenScraper-Konto?", a2: "Ja. Das Konto ist kostenlos und wird auf <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a> erstellt. Das Programm hält die Grenzen deines Kontos ein: Threads, Anfragen pro Minute und Tageskontingent.",
  q3: "Kann es meine Sammlung beschädigen?", a3: "Nein. Dein ROM-Ordner wird nie verändert: Das Programm arbeitet mit einer Kopie im Ausgabeordner, bewahrt frühere Versionen jeder Gamelist auf und löscht nichts.",
  q4: "In welchen Sprachen gibt es das Programm?", a4: "Spanisch, Englisch, Französisch, Deutsch, Portugiesisch, Russisch und Italienisch. Die Spielbeschreibungen werden in der Sprache deiner Wahl geladen.",
  q5: "Was brauche ich dafür?", a5: "Einen Computer mit Windows oder Linux und einen Bildschirm mit mindestens 1280 × 720. Dein Batocera kann im Netzwerk sein: Die Festplatte muss nicht ausgebaut werden.",
  dl_title: "KukoScrapingFree herunterladen", dl_sub: "Kostenlos · Ohne Installation · Für Windows und Linux",
  dl_win: "Für Windows herunterladen", dl_linux: "Für Linux herunterladen",
  dl_note: "Lade es nur von dieser Website herunter: Das ist der einzige offizielle Download.", dl_version: "Version {v}",
  badge_update: "Aktualisiert sich selbst", q6: "Wie wird das Programm aktualisiert?", a6: "Von selbst. Beim Start prüft es, ob es eine neue Version gibt, zeigt dir die Neuerungen und lädt sie, wenn du zustimmst, herunter, installiert sie und öffnet sich wieder. Deine Daten und dein Ausgabeordner bleiben unberührt, und die vorherige Version wird aufbewahrt, falls du zurückwillst. Wenn du 0.5.40 oder älter hast, lade die neue Version einmal von dieser Website herunter: Danach kommen die Updates von selbst.",
  ver_line: "Version {v} · aktualisiert am {d} um {t} Uhr", disc_title: "Haftungsausschluss", disc_text: "KukoScrapingFree wird „wie besehen“ und ohne jede Garantie bereitgestellt und kann Fehler enthalten. <b>Lege eine Sicherung</b> deiner ROMs und deiner gamelist.xml an, bevor du es benutzt und bevor du etwas auf dein Batocera kopierst. Jeder Nutzer ist für die Änderungen an seinem System selbst verantwortlich und nutzt das Programm auf eigenes Risiko: Der Autor haftet nicht für Schäden oder Datenverluste, die es verursachen könnte.", disc_dl: "Mit dem Herunterladen akzeptierst du den <a href=\"#aviso\">Haftungsausschluss</a>.",
  ss_title: "Danke an ScreenScraper",
  ss_text: "Spielinformationen, Bilder und Videos stammen von <a href=\"https://www.screenscraper.fr\">ScreenScraper.fr</a>, einer großen Datenbank, die von ihrer Community aufgebaut und gepflegt wird. Danke, dass dieses Programm eure API nutzen darf. Die Daten und Bilder gehören ScreenScraper und ihren Urhebern.",
  foot_by: "Erstellt von <b>Kukoman</b> · © 2026 · Freeware · <a href=\"https://github.com/kukoxbmc/KukoScrapingFree-web\">GitHub</a>",
  foot_indep: "Unabhängiges Projekt. Batocera und ScreenScraper gehören ihren jeweiligen Inhabern.",
  alt_main: "Hauptfenster von KukoScrapingFree mit der Systemliste und Super-Nintendo-Spielen",
  alt_sheet: "Datenblatt eines Spiels mit Cover, Beschreibung, Galerie und Infos",
  alt_editor: "Kompositionseditor mit Ebenen, Arbeitsfläche und Eigenschaften",
  alt_regions: "Regionseinstellungen mit Flaggen und Reihenfolge",
  alt_mix: "Vom Programm erzeugte Beispielkomposition"
},
pt: {
  meta_title: "KukoScrapingFree — Scraper de ROMs para Batocera",
  meta_desc: "Scraper de ROMs para Batocera Linux: capas, logótipos, vídeos e fichas dos teus jogos a partir do ScreenScraper. Gratuito, em 7 idiomas, para Windows e Linux.",
  nav_features: "Funções", nav_shots: "Capturas", nav_how: "Como funciona", nav_faq: "Perguntas", nav_download: "Descarregar grátis",
  lang_label: "Idioma",
  hero_tag: "Scraper de ROMs para Batocera Linux",
  hero_title: "A tua coleção retro, com capas, logótipos, vídeos e fichas.",
  hero_sub: "O KukoScrapingFree procura cada jogo no ScreenScraper, descarrega os dados e as imagens no teu idioma e deixa-os prontos para o Batocera. Sem nunca tocar na tua pasta de ROMs.",
  btn_download: "Descarregar grátis", btn_how: "Como funciona",
  badge_free: "100 % gratuito", badge_os: "Windows e Linux", badge_langs: "7 idiomas", badge_systems: "256 sistemas do Batocera",
  stats_visits: "Visitas ao site", stats_downloads: "Transferências", stats_win: "Windows", stats_linux: "Linux",
  stats_note: "As transferências são contadas em tempo real a partir do GitHub.",
  free_title: "Gratuito de verdade, para sempre",
  free_text: "Sem anúncios, sem subscrições e sem funções pagas. Podes usá-lo, copiá-lo e partilhá-lo com quem quiseres.",
  scam_title: "Cobraram-te por ele?",
  scam_text: "Então foste enganado. O KukoScrapingFree nunca é vendido. Descarrega-o só a partir deste site e pede o teu dinheiro de volta a quem to vendeu.",
  feat_kicker: "Funções", feat_title: "Tudo o que o teu Batocera precisa, num só programa",
  feat_sub: "Pensado para coleções grandes e para quem não quer lutar com ficheiros XML.",
  f1_t: "Reconhece a tua coleção", f1_d: "Deteta os 256 sistemas do Batocera pelo nome das pastas, no teu computador ou na rede. Agrupa jogos de vários discos e põe as BIOS de parte.",
  f2_t: "Encontra o jogo exato", f2_d: "Calcula a impressão digital de cada ROM (CRC32, MD5 e SHA1) para que o ScreenScraper a identifique sem dúvidas, mesmo com um nome estranho.",
  f3_t: "As tuas regiões e o teu idioma", f3_d: "Tu decides a ordem: Espanha, Europa, Mundial… Capas, nomes e datas vêm da tua região preferida, e a sinopse no teu idioma.",
  f4_t: "As tuas ROMs, intactas", f4_d: "Tudo é guardado numa pasta de saída à parte. Ao copiá-la para o Batocera, os teus jogos jogados e favoritos mantêm-se.",
  f5_t: "Composições ao teu gosto", f5_d: "Um editor visual para desenhar a imagem de cada jogo: captura, caixa 3D, logótipo e textos, com camadas, guias e anular.",
  f6_t: "Ficha completa de cada jogo", f6_d: "Capa, galeria, vídeo integrado e todos os dados. Edita-os à mão ou volta a procurá-los comparando o novo com o que já tens.",
  f7_t: "Rever e limpar", f7_d: "Encontra jogos sem ROM, imagens em falta e ficheiros que ninguém usa. Nada é apagado: o que sobra é posto de parte numa pasta.",
  f8_t: "Tudo pode ser desfeito", f8_d: "Guarda as versões anteriores de cada gamelist. Volta a qualquer uma, ou ao original do Batocera, com um clique.",
  f9_t: "Cuida da tua conta do ScreenScraper", f9_d: "Respeita os limites da tua conta e avisa-te antes de um scraping grande se a quota do dia não chegar.",
  shots_kicker: "Capturas", shots_title: "Assim é por dentro",
  s1_t: "A ficha de cada jogo", s1_d: "Capa, logótipo, composição, sinopse, classificação e todos os dados do jogo num só ecrã. Se algo não te convencer, mudas tu.",
  s2_t: "O editor de composições", s2_d: "Desenha a imagem que vais ver no Batocera colocando camadas, como num programa de desenho. Vê o resultado com os teus jogos antes de o aplicar a todo o sistema.",
  s3_t: "As tuas preferências primeiro", s3_d: "Escolhe e ordena as regiões de onde queres as capas e os nomes. Se a tua região não existir, é usada a seguinte da tua lista.",
  shots_note: "As capturas mostram o programa em espanhol, com jogos de demonstração.",
  mix_title: "Composições geradas automaticamente",
  mix_sub: "Exemplos criados pelo programa com o modelo «Clássico 4:3» (jogos e capas de demonstração).",
  how_kicker: "Como funciona", how_title: "Quatro passos e pronto",
  h1_t: "Descarrega e descomprime", h1_d: "Não se instala nada. Tudo o que o programa guarda fica dentro da sua própria pasta.",
  h2_t: "Escreve a tua conta do ScreenScraper", h2_d: "Só o teu utilizador e palavra-passe do <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. São guardados cifrados no teu computador.",
  h3_t: "Escolhe as tuas pastas", h3_d: "A tua pasta de ROMs, no disco ou na rede (como <code>\\\\BATOCERA\\share\\roms</code>), e onde guardar o resultado. Um assistente guia-te no início.",
  h4_t: "Faz scraping e copia para o Batocera", h4_d: "Marca os sistemas, carrega em «Scraping da seleção» e, no fim, copia a pasta de saída para o teu Batocera.",
  faq_kicker: "Perguntas frequentes", faq_title: "O que se costuma perguntar",
  q1: "Quanto custa?", a1: "Nada. É freeware: gratuito e de livre distribuição, sem anúncios nem funções pagas.",
  q2: "Preciso de uma conta do ScreenScraper?", a2: "Sim. A conta é gratuita e cria-se em <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. O programa respeita os limites da tua conta: threads, pedidos por minuto e quota diária.",
  q3: "Pode estragar a minha coleção?", a3: "Não. A tua pasta de ROMs nunca é modificada: o programa trabalha numa cópia na pasta de saída, guarda as versões anteriores de cada gamelist e não apaga nada.",
  q4: "Em que idiomas está?", a4: "Espanhol, inglês, francês, alemão, português, russo e italiano. A sinopse dos jogos é descarregada no idioma que escolheres.",
  q5: "O que preciso para o usar?", a5: "Um computador com Windows ou Linux e um ecrã de pelo menos 1280 × 720. O teu Batocera pode estar na rede: não é preciso tirar o disco.",
  dl_title: "Descarregar o KukoScrapingFree", dl_sub: "Gratuito · Sem instalação · Para Windows e Linux",
  dl_win: "Descarregar para Windows", dl_linux: "Descarregar para Linux",
  dl_note: "Descarrega-o só a partir deste site: é a única transferência oficial.", dl_version: "Versão {v}",
  badge_update: "Atualiza-se sozinho", q6: "Como se atualiza o programa?", a6: "Sozinho. Ao abrir, verifica se há uma versão nova, mostra-te as novidades e, se aceitares, descarrega-a, instala-a e volta a abrir. Os teus dados e a tua pasta de saída não são alterados, e a versão anterior fica guardada caso queiras voltar a ela. Se tens a 0.5.40 ou anterior, descarrega a nova a partir deste site uma única vez: a partir daí, as atualizações chegam sozinhas.",
  ver_line: "Versão {v} · atualizada a {d} às {t}", disc_title: "Exclusão de responsabilidade", disc_text: "O KukoScrapingFree é fornecido «tal como está», sem qualquer garantia, e pode conter erros. <b>Faz uma cópia de segurança</b> das tuas ROMs e dos teus gamelist.xml antes de o usares e antes de copiares o que quer que seja para o teu Batocera. Cada utilizador é responsável pelas alterações que faz ao seu sistema e usa o programa por sua conta e risco: o autor não se responsabiliza por danos nem por perdas de dados que possa causar.", disc_dl: "Ao descarregá-lo, aceitas a <a href=\"#aviso\">exclusão de responsabilidade</a>.",
  ss_title: "Obrigado ao ScreenScraper",
  ss_text: "A informação, as imagens e os vídeos dos jogos vêm do <a href=\"https://www.screenscraper.fr\">ScreenScraper.fr</a>, uma grande base de dados criada e mantida pela sua comunidade. Obrigado por permitirem que este programa use a vossa API. Os dados e as imagens pertencem ao ScreenScraper e aos seus autores.",
  foot_by: "Criado por <b>Kukoman</b> · © 2026 · Freeware · <a href=\"https://github.com/kukoxbmc/KukoScrapingFree-web\">GitHub</a>",
  foot_indep: "Projeto independente. O Batocera e o ScreenScraper pertencem aos respetivos autores.",
  alt_main: "Janela principal do KukoScrapingFree com a lista de sistemas e jogos da Super Nintendo",
  alt_sheet: "Ficha de um jogo com capa, sinopse, galeria e informação",
  alt_editor: "Editor de composições com camadas, tela e propriedades",
  alt_regions: "Definições de regiões com bandeiras e ordem de preferência",
  alt_mix: "Composição de exemplo gerada pelo programa"
},
ru: {
  meta_title: "KukoScrapingFree — скрапер ROM для Batocera",
  meta_desc: "Скрапер ROM для Batocera Linux: обложки, логотипы, видео и описания игр из ScreenScraper. Бесплатно, на 7 языках, для Windows и Linux.",
  nav_features: "Возможности", nav_shots: "Скриншоты", nav_how: "Как это работает", nav_faq: "Вопросы", nav_download: "Скачать бесплатно",
  lang_label: "Язык",
  hero_tag: "Скрапер ROM для Batocera Linux",
  hero_title: "Ваша ретро-коллекция — с обложками, логотипами, видео и описаниями.",
  hero_sub: "KukoScrapingFree находит каждую игру в ScreenScraper, загружает данные и изображения на вашем языке и готовит их для Batocera. Никогда не изменяя вашу папку с ROM.",
  btn_download: "Скачать бесплатно", btn_how: "Как это работает",
  badge_free: "100 % бесплатно", badge_os: "Windows и Linux", badge_langs: "7 языков", badge_systems: "256 систем Batocera",
  stats_visits: "Посещения сайта", stats_downloads: "Загрузки", stats_win: "Windows", stats_linux: "Linux",
  stats_note: "Загрузки подсчитываются в реальном времени на GitHub.",
  free_title: "Действительно бесплатно — и навсегда",
  free_text: "Без рекламы, подписок и платных функций. Пользуйтесь, копируйте и делитесь с кем угодно.",
  scam_title: "С вас взяли деньги?",
  scam_text: "Значит, вас обманули. KukoScrapingFree никогда не продаётся. Скачивайте его только с этого сайта и потребуйте деньги обратно у продавца.",
  feat_kicker: "Возможности", feat_title: "Всё, что нужно вашей Batocera, в одной программе",
  feat_sub: "Создана для больших коллекций и для тех, кто не хочет возиться с XML-файлами.",
  f1_t: "Распознаёт вашу коллекцию", f1_d: "Определяет все 256 систем Batocera по именам папок — на компьютере или в сети. Объединяет многодисковые игры и откладывает BIOS.",
  f2_t: "Находит точную игру", f2_d: "Вычисляет отпечаток каждого ROM (CRC32, MD5 и SHA1), чтобы ScreenScraper точно его опознал, даже если у файла странное имя.",
  f3_t: "Ваши регионы и ваш язык", f3_d: "Вы задаёте порядок: Испания, Европа, весь мир… Обложки, названия и даты берутся из предпочитаемого региона, а описание — на вашем языке.",
  f4_t: "Ваши ROM не изменяются", f4_d: "Всё сохраняется в отдельную папку вывода. При копировании в Batocera сохраняется история игр и избранное.",
  f5_t: "Композиции на ваш вкус", f5_d: "Визуальный редактор для изображения каждой игры: скриншот, 3D-коробка, логотип и тексты — со слоями, направляющими и отменой.",
  f6_t: "Полная карточка каждой игры", f6_d: "Обложка, галерея, встроенное видео и все данные. Редактируйте вручную или ищите заново, сравнивая новое с тем, что уже есть.",
  f7_t: "Проверка и очистка", f7_d: "Находит игры без ROM, недостающие изображения и неиспользуемые файлы. Ничего не удаляется: лишнее откладывается в отдельную папку.",
  f8_t: "Всё можно отменить", f8_d: "Хранит прежние версии каждого gamelist. Вернитесь к любой из них или к оригиналу Batocera одним щелчком.",
  f9_t: "Бережёт ваш аккаунт ScreenScraper", f9_d: "Соблюдает ограничения аккаунта и предупреждает перед большим скрапингом, если дневной квоты не хватит.",
  shots_kicker: "Скриншоты", shots_title: "Как это выглядит",
  s1_t: "Карточка каждой игры", s1_d: "Обложка, логотип, композиция, описание, оценка и все данные игры на одном экране. Если что-то не нравится — измените сами.",
  s2_t: "Редактор композиций", s2_d: "Создайте изображение для Batocera, расставляя слои, как в графическом редакторе. Проверьте результат на своих играх, прежде чем применить ко всей системе.",
  s3_t: "Сначала ваши предпочтения", s3_d: "Выберите и упорядочьте регионы, из которых брать обложки и названия. Если вашего региона нет, используется следующий в списке.",
  shots_note: "На скриншотах программа на испанском языке, с демонстрационными играми.",
  mix_title: "Автоматически созданные композиции",
  mix_sub: "Примеры, созданные программой по шаблону «Классический 4:3» (демонстрационные игры и обложки).",
  how_kicker: "Как это работает", how_title: "Четыре шага — и готово",
  h1_t: "Скачайте и распакуйте", h1_d: "Ничего не устанавливается. Всё, что сохраняет программа, остаётся в её собственной папке.",
  h2_t: "Введите аккаунт ScreenScraper", h2_d: "Только имя пользователя и пароль от <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Они хранятся на вашем компьютере в зашифрованном виде.",
  h3_t: "Выберите папки", h3_d: "Папку с ROM — на диске или в сети (например, <code>\\\\BATOCERA\\share\\roms</code>) — и куда сохранять результат. В начале вас проведёт мастер настройки.",
  h4_t: "Запустите скрапинг и скопируйте в Batocera", h4_d: "Отметьте системы, нажмите «Обработать выбранное», а по завершении скопируйте папку вывода в Batocera.",
  faq_kicker: "Частые вопросы", faq_title: "О чём часто спрашивают",
  q1: "Сколько это стоит?", a1: "Нисколько. Это freeware: бесплатная и свободно распространяемая программа без рекламы и платных функций.",
  q2: "Нужен ли аккаунт ScreenScraper?", a2: "Да. Аккаунт бесплатный, его можно создать на <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Программа соблюдает ограничения аккаунта: потоки, запросы в минуту и дневную квоту.",
  q3: "Может ли программа испортить коллекцию?", a3: "Нет. Ваша папка с ROM никогда не изменяется: программа работает с копией в папке вывода, хранит прежние версии каждого gamelist и ничего не удаляет.",
  q4: "На каких языках она доступна?", a4: "Испанский, английский, французский, немецкий, португальский, русский и итальянский. Описания игр загружаются на выбранном вами языке.",
  q5: "Что нужно для работы?", a5: "Компьютер с Windows или Linux и экран не меньше 1280 × 720. Batocera может быть в сети — диск вынимать не нужно.",
  dl_title: "Скачать KukoScrapingFree", dl_sub: "Бесплатно · Без установки · Для Windows и Linux",
  dl_win: "Скачать для Windows", dl_linux: "Скачать для Linux",
  dl_note: "Скачивайте только с этого сайта: это единственная официальная загрузка.", dl_version: "Версия {v}",
  badge_update: "Обновляется сама", q6: "Как обновляется программа?", a6: "Сама. При запуске она проверяет, вышла ли новая версия, показывает, что нового, и, если вы согласны, загружает её, устанавливает и открывается снова. Ваши данные и папка вывода не затрагиваются, а предыдущая версия сохраняется на случай, если вы захотите к ней вернуться. Если у вас 0.5.40 или более ранняя, скачайте новую с этого сайта один раз: дальше обновления будут приходить сами.",
  ver_line: "Версия {v} · обновлена {d} в {t}", disc_title: "Отказ от ответственности", disc_text: "KukoScrapingFree предоставляется «как есть», без каких-либо гарантий, и может содержать ошибки. <b>Сделайте резервную копию</b> ваших ROM и файлов gamelist.xml перед использованием и перед тем, как что-либо копировать на Batocera. Каждый пользователь сам отвечает за изменения в своей системе и использует программу на свой страх и риск: автор не несёт ответственности за ущерб или потерю данных, которые она может вызвать.", disc_dl: "Скачивая программу, вы принимаете <a href=\"#aviso\">отказ от ответственности</a>.",
  ss_title: "Спасибо ScreenScraper",
  ss_text: "Сведения об играх, изображения и видео берутся с <a href=\"https://www.screenscraper.fr\">ScreenScraper.fr</a> — большой базы данных, созданной и поддерживаемой сообществом. Спасибо за разрешение использовать ваш API в этой программе. Данные и изображения принадлежат ScreenScraper и их авторам.",
  foot_by: "Автор: <b>Kukoman</b> · © 2026 · Freeware · <a href=\"https://github.com/kukoxbmc/KukoScrapingFree-web\">GitHub</a>",
  foot_indep: "Независимый проект. Batocera и ScreenScraper принадлежат их правообладателям.",
  alt_main: "Главное окно KukoScrapingFree со списком систем и играми Super Nintendo",
  alt_sheet: "Карточка игры с обложкой, описанием, галереей и сведениями",
  alt_editor: "Редактор композиций со слоями, холстом и свойствами",
  alt_regions: "Настройки регионов с флагами и порядком предпочтения",
  alt_mix: "Пример композиции, созданной программой"
},
it: {
  meta_title: "KukoScrapingFree — Scraper di ROM per Batocera",
  meta_desc: "Scraper di ROM per Batocera Linux: copertine, loghi, video e schede dei tuoi giochi da ScreenScraper. Gratuito, in 7 lingue, per Windows e Linux.",
  nav_features: "Funzioni", nav_shots: "Schermate", nav_how: "Come funziona", nav_faq: "Domande", nav_download: "Scarica gratis",
  lang_label: "Lingua",
  hero_tag: "Scraper di ROM per Batocera Linux",
  hero_title: "La tua collezione retrò, con copertine, loghi, video e schede.",
  hero_sub: "KukoScrapingFree cerca ogni gioco su ScreenScraper, scarica dati e immagini nella tua lingua e li prepara per Batocera. Senza mai toccare la tua cartella delle ROM.",
  btn_download: "Scarica gratis", btn_how: "Come funziona",
  badge_free: "100% gratuito", badge_os: "Windows e Linux", badge_langs: "7 lingue", badge_systems: "256 sistemi Batocera",
  stats_visits: "Visite al sito", stats_downloads: "Download", stats_win: "Windows", stats_linux: "Linux",
  stats_note: "I download vengono contati in tempo reale da GitHub.",
  free_title: "Gratis davvero, per sempre",
  free_text: "Niente pubblicità, abbonamenti o funzioni a pagamento. Puoi usarlo, copiarlo e condividerlo con chi vuoi.",
  scam_title: "Te l'hanno fatto pagare?",
  scam_text: "Allora sei stato truffato. KukoScrapingFree non si vende mai. Scaricalo solo da questo sito e chiedi il rimborso a chi te l'ha venduto.",
  feat_kicker: "Funzioni", feat_title: "Tutto ciò che serve al tuo Batocera, in un solo programma",
  feat_sub: "Pensato per le collezioni grandi e per chi non vuole combattere con i file XML.",
  f1_t: "Riconosce la tua collezione", f1_d: "Rileva i 256 sistemi di Batocera dal nome delle cartelle, sul computer o in rete. Raggruppa i giochi su più dischi e mette da parte i BIOS.",
  f2_t: "Trova il gioco esatto", f2_d: "Calcola l'impronta di ogni ROM (CRC32, MD5 e SHA1) perché ScreenScraper la identifichi con certezza, anche se il file ha un nome strano.",
  f3_t: "Le tue regioni e la tua lingua", f3_d: "Decidi tu l'ordine: Spagna, Europa, Mondo… Copertine, nomi e date arrivano dalla tua regione preferita, e la trama nella tua lingua.",
  f4_t: "Le tue ROM, intatte", f4_d: "Tutto viene salvato in una cartella di uscita separata. Copiandola su Batocera si mantengono le partite giocate e i preferiti.",
  f5_t: "Composizioni a tuo gusto", f5_d: "Un editor visivo per creare l'immagine di ogni gioco: schermata, scatola 3D, logo e testi, con livelli, guide e annulla.",
  f6_t: "Scheda completa di ogni gioco", f6_d: "Copertina, galleria, video integrato e tutti i dati. Modificali a mano o cercali di nuovo confrontando il nuovo con ciò che hai già.",
  f7_t: "Controlla e pulisci", f7_d: "Trova giochi senza ROM, immagini mancanti e file inutilizzati. Non si cancella nulla: ciò che avanza viene messo da parte in una cartella.",
  f8_t: "Tutto si può annullare", f8_d: "Conserva le versioni precedenti di ogni gamelist. Torna a una qualsiasi, o all'originale di Batocera, con un clic.",
  f9_t: "Rispetta il tuo account ScreenScraper", f9_d: "Rispetta i limiti del tuo account e ti avvisa prima di uno scraping grande se la quota del giorno non basta.",
  shots_kicker: "Schermate", shots_title: "Uno sguardo all'interno",
  s1_t: "La scheda di ogni gioco", s1_d: "Copertina, logo, composizione, trama, voto e tutti i dati del gioco in un'unica schermata. Se qualcosa non ti convince, lo cambi tu.",
  s2_t: "L'editor di composizioni", s2_d: "Crea l'immagine che vedrai in Batocera disponendo livelli, come in un programma di disegno. Guarda il risultato con i tuoi giochi prima di applicarlo a tutto il sistema.",
  s3_t: "Prima le tue preferenze", s3_d: "Scegli e ordina le regioni da cui prendere copertine e nomi. Se la tua regione non c'è, si usa la successiva della tua lista.",
  shots_note: "Le schermate mostrano il programma in spagnolo, con giochi dimostrativi.",
  mix_title: "Composizioni generate automaticamente",
  mix_sub: "Esempi creati dal programma con il modello «Classico 4:3» (giochi e copertine dimostrativi).",
  how_kicker: "Come funziona", how_title: "Quattro passi ed è fatta",
  h1_t: "Scarica ed estrai", h1_d: "Non si installa nulla. Tutto ciò che il programma salva resta nella sua cartella.",
  h2_t: "Inserisci il tuo account ScreenScraper", h2_d: "Solo nome utente e password di <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Vengono salvati cifrati sul tuo computer.",
  h3_t: "Scegli le cartelle", h3_d: "La cartella delle ROM, sul disco o in rete (come <code>\\\\BATOCERA\\share\\roms</code>), e dove salvare il risultato. Una procedura guidata ti accompagna all'inizio.",
  h4_t: "Fai lo scraping e copia su Batocera", h4_d: "Seleziona i sistemi, premi «Elabora selezione» e, alla fine, copia la cartella di uscita sul tuo Batocera.",
  faq_kicker: "Domande frequenti", faq_title: "Le domande più comuni",
  q1: "Quanto costa?", a1: "Niente. È freeware: gratuito e liberamente distribuibile, senza pubblicità né funzioni a pagamento.",
  q2: "Serve un account ScreenScraper?", a2: "Sì. L'account è gratuito e si crea su <a href=\"https://www.screenscraper.fr\">screenscraper.fr</a>. Il programma rispetta i limiti del tuo account: thread, richieste al minuto e quota giornaliera.",
  q3: "Può rovinare la mia collezione?", a3: "No. La cartella delle ROM non viene mai modificata: il programma lavora su una copia nella cartella di uscita, conserva le versioni precedenti di ogni gamelist e non cancella nulla.",
  q4: "In quali lingue è disponibile?", a4: "Spagnolo, inglese, francese, tedesco, portoghese, russo e italiano. Le trame dei giochi vengono scaricate nella lingua che scegli.",
  q5: "Cosa serve per usarlo?", a5: "Un computer con Windows o Linux e uno schermo di almeno 1280 × 720. Il tuo Batocera può essere in rete: non serve togliere il disco.",
  dl_title: "Scarica KukoScrapingFree", dl_sub: "Gratuito · Senza installazione · Per Windows e Linux",
  dl_win: "Scarica per Windows", dl_linux: "Scarica per Linux",
  dl_note: "Scaricalo solo da questo sito: è l’unico download ufficiale.", dl_version: "Versione {v}",
  badge_update: "Si aggiorna da solo", q6: "Come si aggiorna il programma?", a6: "Da solo. All'avvio controlla se c'è una nuova versione, ti mostra le novità e, se accetti, la scarica, la installa e si riapre. I tuoi dati e la cartella di uscita non vengono toccati, e la versione precedente viene conservata nel caso tu voglia tornarci. Se hai la 0.5.40 o una precedente, scarica la nuova da questo sito una sola volta: da lì in poi gli aggiornamenti arriveranno da soli.",
  ver_line: "Versione {v} · aggiornata il {d} alle {t}", disc_title: "Esclusione di responsabilità", disc_text: "KukoScrapingFree viene fornito «così com'è», senza alcuna garanzia, e può contenere errori. <b>Fai un backup</b> delle tue ROM e dei tuoi gamelist.xml prima di usarlo e prima di copiare qualsiasi cosa sul tuo Batocera. Ogni utente è responsabile delle modifiche che apporta al proprio sistema e usa il programma a proprio rischio: l'autore non è responsabile di danni o perdite di dati che potrebbe causare.", disc_dl: "Scaricandolo accetti l'<a href=\"#aviso\">esclusione di responsabilità</a>.",
  ss_title: "Grazie a ScreenScraper",
  ss_text: "Informazioni, immagini e video dei giochi provengono da <a href=\"https://www.screenscraper.fr\">ScreenScraper.fr</a>, un grande database creato e mantenuto dalla sua comunità. Grazie per aver permesso a questo programma di usare la vostra API. I dati e le immagini appartengono a ScreenScraper e ai rispettivi autori.",
  foot_by: "Creato da <b>Kukoman</b> · © 2026 · Freeware · <a href=\"https://github.com/kukoxbmc/KukoScrapingFree-web\">GitHub</a>",
  foot_indep: "Progetto indipendente. Batocera e ScreenScraper appartengono ai rispettivi proprietari.",
  alt_main: "Finestra principale di KukoScrapingFree con l'elenco dei sistemi e i giochi Super Nintendo",
  alt_sheet: "Scheda di un gioco con copertina, trama, galleria e informazioni",
  alt_editor: "Editor di composizioni con livelli, tela e proprietà",
  alt_regions: "Impostazioni delle regioni con bandiere e ordine di preferenza",
  alt_mix: "Composizione di esempio generata dal programma"
}
};
